jobs:
    pypi-publish:
        name: Publish Release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/grid20m
        permissions:
            id-token: write
        steps:
        - name: pypi-publish
          uses: pypa/gh-action-pypi-publish@v1.8.14
